# # Labels for landmarks
# Landmarks = st_read("C:/users/keppele/documents/cemore/analysis/cemore_sdm/data/Labels.csv", stringsAsFactors = F,
# options=c("X_POSSIBLE_NAMES=LONG","Y_POSSIBLE_NAMES=LAT")) %>%
#   st_set_crs(4326) %>%
#   # st_transform(EPSGcode) %>%
#   mutate(Label = case_when(Label == "La Perouse Bank" ~ "La P\u00E9rouse Bank",
#                            Label == "San Juan Isl" ~ "San\nJuan\nIsl",
#                            Label == "Swiftsure Bank" ~ "Swiftsure\nBank",
#                            Label == "Salmon Bank" ~ "Salmon\nBank",
#                            Label == "Saturna Isl" ~ "Saturna\nIsl",
#                            Label == "Pender Isls" ~ "Pender\nIsls",
#                            Label == "Strait of Juan de Fuca" ~ "Juan de Fuca Strait",
#                            Label == "Swanson Channel" ~ "Swanson\nCh.",
#                            Label == "Carmanah Point" ~ "Carmanah Pt",
#                            Label == "VANCOUVER ISLAND" ~ "Vancouver Island",
#                            Label == "Lopez Isl" ~ "Lopez\nIsl",
#                            Label == "Port San Juan" ~ "Port San\nJuan",
#                            T ~ Label),
#          FontFace = case_when(Subtype == "Waterway" ~ "italic",
#                               T ~ "plain"),
#          FontCol = case_when(Subtype == "Waterway" ~ "white",
#                              # Label == "Swiftsure\nBank" ~ "white",
#                              # Label == "Boundary Pass" ~ "white",
#                              # Label == "Haro Strait" ~ "white",
#                              # Label == "Salmon\nBank" ~ "white",
#                              # Label == "Strait of Georgia" ~ "white",
#                              # Subtype == "Waterway" ~ "dodgerblue3",
#                              T ~ "black"),
#          FontSize = case_when(Label %in% c("Pender\nIsls", "Saturna\nIsl","Salmon\nBank", "Swanson\nCh.", "Fraser River","Victoria","Lopez\nIsl","Port San\nJuan") ~ 3.3,
#                               T ~ 4),
#          nudgeY = case_when(Label == "Vancouver Island" ~ -10000,
#                             Label == "Vancouver" ~ -1500,
#                             Label == "Nitinat" ~ 0,
#                             Label == "Port Renfrew" ~ -1000,
#                             Label == "Jordan River" ~ 3500,
#                             Label == "Sooke" ~ 3500,
#                             Label == "Victoria" ~ 5000,
#                             Label == "Port Angeles" ~ -3500,
#                             Label == "Neah Bay" ~ -7000,
#                             Label == "La P\u00E9rouse Bank" ~ -5000,
#                             Label == "Port San\nJuan" ~ 5000,
#                             Label == "Haro Strait" ~ -3000,
#                             Label == "San\nJuan\nIsl" ~ -1000,
#                             Label == "Swiftsure\nBank" ~ -2500,
#                             Label == "Juan de Fuca Strait" ~ -4000,
#                             Label == "Pender\nIsls" ~ -1500,
#                             Label == "Fraser River" ~ 0,
#                             Label == "Strait of Georgia" ~ -30000,
#                             Label == "WASHINGTON" ~ 18000,
#                             Label == "Swanson\nCh." ~ 10000,
#                             Label == "Cape Flattery" ~ -6000,
#                             Label == "Lopez\nIsl" ~ -1000,
#                             TRUE ~ 0),
#          nudgeX = case_when(Label == "Vancouver" ~ 11000,
#                             Label == "Nitinat" ~ 9000,
#                             Label == "Port Renfrew" ~ 13000,
#                             Label == "Jordan River" ~ 5000,
#                             Label == "Sooke" ~ -4000,
#                             Label == "Victoria" ~ -3000,
#                             Label == "Neah Bay" ~ 10000,
#                             Label == "San\nJuan\nIsl" ~ 1300,
#                             Label == "Swiftsure\nBank" ~ 3000,
#                             Label == "Port San\nJuan" ~ - 8000,
#                             Label == "Pender\nIsls" ~ 1000,
#                             Label == "Haro Strait" ~ 2000,
#                             Label == "Fraser River" ~ 6000,
#                             Label == "WASHINGTON" ~ -16000,
#                             Label == "Strait of Georgia" ~ 30000,
#                             Label == "Swanson\nCh." ~ -4500,
#                             Label == "Carmanah Pt" ~ 12000,
#                             Label == "Cape Flattery" ~ 12000,
#                             Label == "Orcas Isl" ~ 4000,
#                             Label == "Vancouver Island" ~ -4000,
#                             TRUE ~ 0),
#          rot = case_when(Label == "Juan de Fuca Strait" ~ -21,
#                          Label == "Neah Bay" ~ -27,
#                          Label == "Haro Strait" ~ -70,
#                          Label == "Boundary Pass" ~ 20,
#                          Label == "Fraser River" ~ 0,
#                          Label == "Strait of Georgia" ~ -40,
#                          Label == "Cape Flattery" ~ -23,
#                          TRUE ~ 0)) %>%
#   dplyr::filter(!Label %in% c("Neah Bay", "Pender\nIsls", "Saturna\nIsl","Victoria",
#                               "Salmon\nBank", "Carmanah Pt", "Port Renfrew"))
#
# Landmarks_simp = Landmarks %>%
#   dplyr::filter(Label %in% c("Swiftsure\nBank", "Vancouver Island",
#                              "WASHINGTON","Haro Strait")) %>%
#   mutate(FontCol = "black",
#          nudgeY = case_when(Label == "Vancouver Island" ~ 14000,
#                             Label == "WASHINGTON" ~ -12000,
#                             T ~ nudgeY),
#          nudgeX = case_when(Label == "WASHINGTON" ~ 30000,
#                             T ~ nudgeX),
#          Label = case_when(Label == "Vancouver Island" ~ "Vancouver Island\nBRITISH COLUMBIA",
#                            T ~ Label))
#
# # Country_labs = st_as_sf(data.frame(Label = c("CANADA","USA",
# #                                              "BRITISH\nCOLUMBIA",
# #                                              "WASHINGTON\nSTATE"),
# #                                    Fig_complex = c("Yes","Yes","No","No"),
# #                                    Fig_simp = c("Yes","Yes","Yes","Yes"),
# #                                    FontCol = "white",
# #                                    FontFace = "plain",
# #                                    FontSize = c(2,2,3,3),
# #                                    rot = c(5,5,0,0),
# #                                    nudgeX = c(0,0,27000,20000),
# #                                    nudgeY = c(0,0,-13000,3000),
# #                                    lat = c(49.06,48.95,49.07,47.5),
# #                                    lon = c(-122.5,-122.5,-124.7,-124)),
# #                         coords = c("lon","lat"),
# #                         crs = 4326) %>%
# #   st_transform(EPSGcode)
# #
# # Bank_labs = st_as_sf(data.frame(Label = c("Hein\nBank",
# #                                           "Salmon\nBank",
# #                                           "Middle\nBank"),
# #                                 FontCol = "white",
# #                                 FontFace = "bold.italic",
# #                                 FontSize = c(2.8,2.8,2.8),
# #                                 rot = c(0,0,0),
# #                                 nudgeX = c(1000,7000,-1500),
# #                                 nudgeY = c(-2500,-10500,-1500),
# #                                 lat = c(48.338445,
# #                                         48.42737,
# #                                         48.409371),
# #                                 lon = c(-123.08053,
# #                                         -122.99058,
# #                                         -123.1062863)),
# #                      coords = c("lon","lat"),
# #                      crs = 4326) %>%
# #   st_transform(EPSGcode)
